azs:
- name: z1

vm_types:
- name: small
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: medium
  cloud_properties:
    cpu: 2
    ram: 2048
    disk: 3240
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240

disk_types:
- name: medium
  disk_size: 3000
- name: large
  disk_size: 100_000

networks:
- name: default
  type: manual
  subnets:
  - range: ((ert_internal_cidr))
    gateway: ((ert_internal_gw))
    azs: [z1]
    dns: [168.63.129.16]
    reserved: []
    static:
    - ((postgres_sql_ip))
    - ((ha_proxy_ip))
    cloud_properties:
      virtual_network_name: ((vnet_name))
      subnet_name: ((ert_subnet_name))
      security_group: ((security_group))
- name: vip
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: large
  network: default
