ha_proxy_ip: 10.193.63.151
default_network: default
dns_server: 10.193.63.2
system_domain: test.shaozhenpcf.com
ha_proxy_certs: |
  -----BEGIN CERTIFICATE-----
  MIIEaDCCA1CgAwIBAgIJAN2so+m/IVvbMA0GCSqGSIb3DQEBBQUAMH8xCzAJBgNV
  BAYTAlVTMQswCQYDVQQIEwJUWDEOMAwGA1UEBxMFQWxsZW4xETAPBgNVBAoTCFNo
  YW96aGVuMR8wHQYDVQQDFBYqLnRlc3QucGNmc2hhb3poZW4uY29tMR8wHQYJKoZI
  hvcNAQkBFhBzZGluZ0BwaXZvdGFsLmlvMB4XDTE3MDUxNzE1MDIwMFoXDTE4MDUx
  NzE1MDIwMFowfzELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAlRYMQ4wDAYDVQQHEwVB
  bGxlbjERMA8GA1UEChMIU2hhb3poZW4xHzAdBgNVBAMUFioudGVzdC5wY2ZzaGFv
  emhlbi5jb20xHzAdBgkqhkiG9w0BCQEWEHNkaW5nQHBpdm90YWwuaW8wggEiMA0G
  CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDkg1Cn98w5jJDf4MpUPgyyK4GarmwV
  /TnJWl0lWBsEGBURXtvhznX+F1NsU6CMO4p1nEY79CDLPwHYs3pc378ypl1ksRAk
  5+DWLVPla2HQW2CgXzfVS2lQAK/UIsmGOigPWaNsW1pQgN2HiNGTLDXFiNiPyQIa
  gfwSbdspS6pxldKWEPyx2TrW+BsrHquxV1/LJNq1zCWAAD2msLZrwIZ4AuBn8dsG
  tJCces+pKcQKWXTrtf+8X/sVQEtvHq22k272vNEeieCxNp8561i0n39HngiEQyJi
  XrejWZHBd+0zV1xqlDS5P7/y7PvYJTjD5wT9nrp4yb9DFcRiPYZcWb4tAgMBAAGj
  geYwgeMwHQYDVR0OBBYEFOUx4tS2nFrz8nlLtE0i3BWJ/D7wMIGzBgNVHSMEgasw
  gaiAFOUx4tS2nFrz8nlLtE0i3BWJ/D7woYGEpIGBMH8xCzAJBgNVBAYTAlVTMQsw
  CQYDVQQIEwJUWDEOMAwGA1UEBxMFQWxsZW4xETAPBgNVBAoTCFNoYW96aGVuMR8w
  HQYDVQQDFBYqLnRlc3QucGNmc2hhb3poZW4uY29tMR8wHQYJKoZIhvcNAQkBFhBz
  ZGluZ0BwaXZvdGFsLmlvggkA3ayj6b8hW9swDAYDVR0TBAUwAwEB/zANBgkqhkiG
  9w0BAQUFAAOCAQEA1laH97xRldMlYgTZ3/1FHIyVRbYoOji+jcdBQa+MjrQdiWcS
  DpfLRKrvaJwjoZBYcpfLcaJ67B1GJ+99KgCt/L9QQ9QSuI1sPClU/5oFQsdKj/LP
  6N39XtvQW/KeMxrjg2BmHVtmlTBfHr6nz8EpsIbR3RD6T+URgUE12uhF0Nu+vXxC
  JxuHUcUelv5Ihek03UafGo9rB20LHVseyIqdV+DMCLNqU5XyI33DlcM/JAmNNTj7
  fdArFYmvXGysgweP3VMp+3O1sPNnyJu8uk2P3IiNkS7UBtnA/i8HATvfjkh0dpyf
  qnwbXq2L9RK4ozUzsE7ZdyhyPogWxkB7abr5lQ==
  -----END CERTIFICATE-----
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEA5INQp/fMOYyQ3+DKVD4MsiuBmq5sFf05yVpdJVgbBBgVEV7b
  4c51/hdTbFOgjDuKdZxGO/Qgyz8B2LN6XN+/MqZdZLEQJOfg1i1T5Wth0FtgoF83
  1UtpUACv1CLJhjooD1mjbFtaUIDdh4jRkyw1xYjYj8kCGoH8Em3bKUuqcZXSlhD8
  sdk61vgbKx6rsVdfyyTatcwlgAA9prC2a8CGeALgZ/HbBrSQnHrPqSnECll067X/
  vF/7FUBLbx6ttpNu9rzRHongsTafOetYtJ9/R54IhEMiYl63o1mRwXftM1dcapQ0
  uT+/8uz72CU4w+cE/Z66eMm/QxXEYj2GXFm+LQIDAQABAoIBAQDUb3eGD4neXl04
  pAO0uVKYOHXuVQTKlHUqSUWauAO1lKXRVjxX+dYbd5fodv4kIB4iJDvu9I+gI10W
  FhRFTwSyk5LzTuBRTvfoZI9AEsoGJ0z3Ck4fjlHDPEA5mHV8wYgIbS7OR0b43DQW
  Eg2zIkCC+StK0HWSKxEqGNLL2zoDCKGmta3okhLN69MKCxb+qGmaFCw3bQOkdz+e
  sKyLPrOmU1ESiWvYRHAVLeVZdrb5Xp7cAkpDNbr/Bwwtpq2KSj+CjWfOd+ZVchJD
  7nh3MVjBi+/f04TZF+SKqS1nzdF92qB9bnYecE57PXselDK6MGsc6FgH1jwMzKyA
  Rb2lebLBAoGBAPmGVqdZPXqIIP5K4MWLfuj8QepvSCMjF1Gq0PApPeYv2SNNK6p8
  5Q3IsQlIHaVrAjpwfMFpaEiYfUBMfVCvuCWJuhBnNilQ+4+tUMOuR8lsE16mYEZC
  +8XFvLF2+HLH9wUmzSllNuOuQFtsvaX7se3U4Xe2vEOO1Dgb6gkdHVhpAoGBAOpx
  Y6wnlw5i3Q78O9gbPh8ubaohyV5NCBlUhdmweZrw9nzIpLMSxZoIBnjgAlx0vpEn
  YC0mL0Ld93GJ//duX5yANY9HLoS4tf2IJZXEBZtoV3iUlXN8gQxTjxxW2sUWTknV
  4zcS5W9q+Eh3gjlmO6PL/Zp9wVR2lCZ17oUXRV8lAoGAXws3iIjqbPjbMGFPGo/W
  6GHlralzncapBDd/XGspI7vIBrVHU6o9CTIPlQx+FlsbPy1Hp9hBm51R4CMCfLBi
  ARJj6AmYTMaG+6Q1pkOFHojnG99dvoWXJy75f9NkMTxPsAumjAT8kl72LpzN5CJq
  FMBInXPiZA1Mco7XZ19KpTkCgYB+7akDGeQku83nQRS9afJ2O1LQW76EObx6ylI1
  i+AqzO8GnDLfaPhm7pVieBWPLP3H5MOjbhsEXtyLMiXNNoq5Voio6+b5oG+XtlBz
  B0/p1dIVzIwlnHDZ1ZuTwkprjioQu6ZquOZTLl0CDwIIRZtgkR7at98l9ZU8RXk/
  wVujqQKBgF2o6+Lt2ve0kS9K4vDOZtGcFnPmizwqxYjgUYN1eLG9Qzo7ADffaSkw
  HJcTYIBMrj/TqTn1KniP0ruj8nVu0EpZaful95FbLrztZPQ98RA8Q3pt3AUyEKqa
  9jUXmu8LOpder4mNEBs3F7bBSquNj9nvqiQ9yWxozlWwJNPm2hIe
  -----END RSA PRIVATE KEY-----
