#!/bin/bash
set -e

source lib/common.sh
iaas=$1
check_argument ${iaas}



director=$(bosh-cli int ${iaas}/director.yml --path /internal_ip)
director_name=$(bosh-cli int ${iaas}/director.yml --path /director_name)

export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET=$(bosh-cli int ${iaas}/creds.yml --path /admin_password)

bosh-cli -n -e https://${director}:25555 alias-env ${director_name} \
  --ca-cert <(bosh-cli int ${iaas}/creds.yml --path /default_ca/ca)

stemcell_url=$(bosh-cli int stemcell_metadata.yml --path /${iaas})

bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.2.0
bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/concourse/concourse?v=3.3.4
bosh-cli -e ${director_name} upload-stemcell ${stemcell_url}
