#!/bin/bash
set -e

source lib/common.sh
iaas=$1
check_argument ${iaas}



director=$(bosh-cli int ${iaas}/director.yml --path /internal_ip)
director_name=$(bosh-cli int ${iaas}/director.yml --path /director_name)

export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET=$(bosh-cli int ${iaas}/creds.yml --path /admin_password)

bosh-cli -n -e https://${director}:25555 alias-env ${director_name} \
  --ca-cert <(bosh-cli int ${iaas}/creds.yml --path /default_ca/ca)

stemcell_url=$(bosh-cli int stemcell_metadata.yml --path /${iaas})

bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry/diego-release?v=1.18.1
bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry/cf-release?v=272
bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.2.0
bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-rootfs-release?v=1.60.0
bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry-incubator/consul-release?v=159
bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry/capi-release?v=1.28.0
bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry/loggregator?v=89
bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=32
bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry-incubator/cf-networking-release?v=1.6.0
bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry/cf-mysql-release?v=36
bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.162.0
bosh-cli -e ${director_name} upload-release https://bosh.io/d/github.com/cloudfoundry/statsd-injector-release?v=1.0.30
bosh-cli -e ${director_name} upload-stemcell ${stemcell_url}
