azs:
- name: z1
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]

vm_types:
- name: small
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: medium
  cloud_properties:
    cpu: 2
    ram: 2048
    disk: 3240
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240
- name: compilation
  cloud_properties:
    cpu: 4
    ram: 4096
    disk: 30_240

- cloud_properties:
    cpu: 1
    disk: 20480
    ram: 4096
  name: minimal
- cloud_properties:
    cpu: 1
    disk: 20480
    ram: 4096
  name: master
- cloud_properties:
    cpu: 4
    disk: 102400
    ram: 8192
  name: worker

disk_types:
- name: medium
  disk_size: 3000
- name: large
  disk_size: 100_000

networks:
- name: default
  type: manual
  subnets:
  - range: ((ert_internal_cidr))
    gateway: ((ert_internal_gw))
    azs: [z1]
    dns: [((dns_server))]
    reserved: []
    static:
    - ((ha_proxy_ip))
    cloud_properties:
      name: ((ert_network_name))
- name: kubo
  subnets:
  - azs:
    - z1
    cloud_properties:
      name: ((kubo_network_name))
    dns: [((kubo_dns_server))]
    gateway: ((kubo_internal_gw))
    range: ((kubo_internal_cidr))
    reserved: ((kubo_reserved_ips))
    static: []
  type: manual

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: compilation
  network: default
