- type: replace
  path: /vm_extensions?
  value:
  - name: web_load_balancer
    cloud_properties:
      backend_service: ((cf_public_backend_service))
      tags:
        - ((cf_public_firewall_tag))
